// Code generated by typeid-sqlc-shim. DO NOT EDIT

package testdata

import "go.jetify.com/typeid"

type UserPrefix string

func (p UserPrefix) Prefix() string {
	return "usr"
}

type OrganizationPrefix string

func (p OrganizationPrefix) Prefix() string {
	return "org"
}

type TeamPrefix string

func (p TeamPrefix) Prefix() string {
	return "team"
}

type ProjectPrefix string

func (p ProjectPrefix) Prefix() string {
	return "proj"
}

type UserID struct {
	typeid.TypeID[UserPrefix]
}

type OrganizationID struct {
	typeid.TypeID[OrganizationPrefix]
}

type TeamID struct {
	typeid.TypeID[TeamPrefix]
}

type ProjectID struct {
	typeid.TypeID[ProjectPrefix]
}

func NewID[T typeid.Subtype, PT typeid.SubtypePtr[T]]() T {
	return typeid.Must(typeid.New[T, PT]())
}
